version: '3.8'

services:
  database:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass12345
      POSTGRES_DB: parking_db
    ports:
      - "5433:5432"
    volumes:
      - parking_db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./be-parking-pos
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    expose:
      - 8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/parking_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass12345
    depends_on:
      - database

  frontend:
    build:
      context: ./fe-parking-pos
      dockerfile: Dockerfile.frontend
    restart: always
    ports:
      - "3000:3000"
    expose:
      - 3000
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://127.0.0.1:8080
    depends_on:
      - backend

volumes:
  parking_db_data:
